{{- if .Values.job.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-components-stack.fullname" . }}-hooks
  labels:
    {{- include "kube-components-stack.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-components-stack.fullname" . }}-hooks
  labels:
    {{- include "kube-components-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-components-stack.fullname" . }}-hooks
subjects:
- kind: ServiceAccount
  name: {{ include "kube-components-stack.serviceAccountName" . }}-hooks
  namespace: {{ .Release.Namespace }}
{{- end }}