{{- range $path, $_ := .Files.Glob "modrules/*.yaml" }}
{{- range ( $.Files.Get $path | fromYamlArray ) }}

---

apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: {{ include "kubemod-with-modrules.fullname" $ }}-{{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "kubemod-with-modrules.labels" $ | nindent 4 }}
spec:
{{ toYaml .spec | indent 2 }}


{{- end }}
{{- end }}