#!/bin/bash

function update_charts () {
  set -euo pipefail
  local tempfile=$(mktemp /tmp/Chart.XXXXXXXXXX)
  local src_file=Chart.yaml
  local charts=$(yq -o=json $src_file | jq '[.dependencies[] | { chart: .name, repoURL: .repository, targetRevision: .version }]')
  
  local rows=$(echo "${charts}" | jq -r '.[] | @base64')
  local nb=$(echo "$rows"|wc -l)

  for row in $rows; do
    _jq() {
     echo ${row} | base64 --decode | jq -r ${1}
    }
    local chart=$(echo $(_jq '.chart'))
    local repoURL=$(echo $(_jq '.repoURL'))
    local targetRevision=$(echo $(_jq '.targetRevision'))

    helm repo add $chart --force-update $repoURL &> /dev/null
    local version=$(helm search repo $chart/$chart -o json | jq -r --arg name $chart/$chart '.[] | select(.name == $name) | .version')
    yq -i '.dependencies[] |= select(.name == "'$chart'").version="'$version'"' $src_file
    if [[ $nb -eq 1 ]]; then
      local app_version=$(helm search repo $chart/$chart -o json | jq -r --arg name $chart/$chart '.[] | select(.name == $name) | .app_version')
      yq -i '.appVersion ="'$app_version'"' $src_file
    fi
  done

  helm dependency update
}

# Allows to call a function based on arguments passed to the script
$*