name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.8.1

      - name: Add dependency chart repos
        run: |
          helm repo add cert-manager https://charts.jetstack.io
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
          helm repo add kubemod https://malibukoko.github.io/kubemod-helm
          helm repo add argocd-notifications https://argoproj.github.io/argo-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"